#!/usr/bin/env ruby

require 'fileutils'
require 'open-uri'

# ToDo: I guess I will create a small gem out of that.

system "mkdir -p /tmp/home_cookin"

File.open("/tmp/home_cookin/cook", 'w+') do |f|
  open("https://github.com/gvarela/home_cookin/raw/master/cook") { |r| f.write(r.read) }
end

FileUtils.chmod 0755, "/tmp/home_cookin/cook"

File.open("#{ENV['HOME']}/.cook", 'w+') do |f|
  open("https://github.com/gvarela/home_cookin/raw/master/default.json") { |r| f.write(r.read) }
end

usage = <<-END
To update from your cookbooks run
 sudo /tmp/home_cookin/cook node.json
END

puts usage
